// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using case_reviews_server.Data;

#nullable disable

namespace case_reviews_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230710182041_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("case_reviews_server.Data.MagiEligibles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultsEligibleActual")
                        .HasColumnType("integer");

                    b.Property<int>("AdultsEligibleCoded")
                        .HasColumnType("integer");

                    b.Property<int>("AdultsNotEligibleActual")
                        .HasColumnType("integer");

                    b.Property<int>("AdultsNotEligibleCoded")
                        .HasColumnType("integer");

                    b.Property<int>("ChildrenEligibleActual")
                        .HasColumnType("integer");

                    b.Property<int>("ChildrenEligibleCoded")
                        .HasColumnType("integer");

                    b.Property<int>("ChildrenNotEligibleActual")
                        .HasColumnType("integer");

                    b.Property<int>("ChildrenNotEligibleCoded")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique();

                    b.ToTable("MagiEligibles");
                });

            modelBuilder.Entity("case_reviews_server.Data.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaseNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTargeted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MagiSubProgram")
                        .HasColumnType("integer");

                    b.Property<int?>("NonMagiSubProgram")
                        .HasColumnType("integer");

                    b.Property<string>("OtherComments")
                        .HasColumnType("text");

                    b.Property<int>("Program")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportingSystem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("case_reviews_server.Data.ReviewElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasAction")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<int>("Program")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewedElement")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewElements");
                });

            modelBuilder.Entity("case_reviews_server.Data.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ORNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Office")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("case_reviews_server.Data.MagiEligibles", b =>
                {
                    b.HasOne("case_reviews_server.Data.Review", null)
                        .WithOne("MagiEligibles")
                        .HasForeignKey("case_reviews_server.Data.MagiEligibles", "ReviewId");
                });

            modelBuilder.Entity("case_reviews_server.Data.Review", b =>
                {
                    b.HasOne("case_reviews_server.Data.Staff", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("case_reviews_server.Data.ReviewElement", b =>
                {
                    b.HasOne("case_reviews_server.Data.Review", null)
                        .WithMany("ReviewElements")
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("case_reviews_server.Data.Review", b =>
                {
                    b.Navigation("MagiEligibles");

                    b.Navigation("ReviewElements");
                });

            modelBuilder.Entity("case_reviews_server.Data.Staff", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
